getter:
  "http://localhost:8002":
    endpoint: http://localhost:8080/realms/logprep/protocol/openid-connect/token
    username: logprep
    password: logprep
    client_id: fda
    client_secret: tYfkKygb1g2Hf6fmAInoq3XPK1OILbSp
  "http://localhost:3005":
    endpoint: http://localhost:8080/realms/logprep/protocol/openid-connect/token
    username: logprep
    password: logprep
    client_id: ucl
    client_secret: Zq15PsiNvXjCtBUHwG8x8NwaWjJwaB17
  "http://localhost:8081":
    username: user
    password: password
  "https://localhost:8082":
    client_key: quickstart/exampledata/config/nginx/mtls.conf.d/client.key
    cert: quickstart/exampledata/config/nginx/mtls.conf.d/client.crt
    ca_cert: quickstart/exampledata/config/nginx/mtls.conf.d/ca.crt
input:
  endpoints:
    /auth-json:
      username: user
      password_file: quickstart/exampledata/config/user_password.txt
    /lab/123/ABC/auditlog:
      username: user
      password_file: quickstart/exampledata/config/user_password.txt
