{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "logprep.serviceAccountName" .}}
  labels:
    {{- include "logprep.labels" . | nindent 4}}
spec:
  automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
