{{- if and .Values.serviceAccount.create .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "logprep.serviceAccountName" .}}
  labels:
    {{- include "logprep.labels" . | nindent 4}}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
